In [2]:
import pandas as pd
import numpy as np

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics
import joblib

In [3]:
import torch

In [ ]:
x, y = torch.rand(2, 3), torch.rand(2, 3)
print(x)
print(y)

In [ ]:
a = torch.autograd.Variable(torch.ones(2, 2), requires_grad=True)
a

In [ ]:
z = a ** 2 + 2 * a + 5
z

In [ ]:
z.backward(torch.ones(2, 2))
print(a.grad)

In [4]:
import torch.nn as nn
import torch.nn.functional as F

In [59]:
class OurNet(nn.Module):

    def __init__(self):
        super(OurNet, self).__init__()
        self.fc1 = nn.Linear(3, 200)
        self.fc2 = nn.Linear(200, 200)
        self.fc3 = nn.Linear(200, 2)


    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return F.softmax(F.normalize(x.abs()))


In [47]:
net = OurNet()
print(net)

OurNet(
  (fc1): Linear(in_features=3, out_features=200, bias=True)
  (fc2): Linear(in_features=200, out_features=2, bias=True)
)


In [48]:
loss_fun = nn.BCELoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)

In [16]:
def get_data(name):
    train = pd.read_csv(name)
    train = train[["pclass", "age", "sex", 'survived']]
    median = train['age'].median()
    train['age'].fillna(median, inplace=True)
    train['pclass'].replace('3rd', 3, inplace=True)
    train['pclass'].replace('2nd', 2, inplace=True)
    train['pclass'].replace('1st', 1, inplace=True)
    train['sex'] = np.where(train['sex'] == 'female', 0, 1)
    return train
train_data = get_data("data/titanic_train.csv")
test_data = get_data("data/titanic_test.csv")

In [60]:
X = torch.Tensor(train_data[["pclass", "age", "sex"]].to_numpy())
Y = torch.Tensor(train_data[["survived"]].to_numpy())

In [61]:
Y_new = torch.Tensor(len(Y), 2)
for i in range(len(Y)):
    print(Y[i])
    if np.abs(Y[i]) < 1.e-10:
        Y_new[i][0] = 1
        Y_new[i][1] = 0
    else:
        Y_new[i][0] = 0
        Y_new[i][1] = 1
Y = Y_new

tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([1.])
tensor([0.])
tensor([0.])
tensor([0.])
tensor([0.])

In [62]:
net = OurNet()
loss_fun = nn.BCELoss()
optimizer = torch.optim.SGD(net.parameters(), lr=0.01)

In [63]:
epochs = 10_000
batch_size = 10

def fit(net, batch_size, X, Y):
    net.train(True)
    sumL, sumA, numB = 0, 0, int(len(X) / batch_size)

    for i in range(0, numB*batch_size, batch_size):
        xb = X[i: i + batch_size]
        yb = Y[i: i + batch_size]

        y_cur = net(xb)
        L = loss_fun(y_cur, yb)

        optimizer.zero_grad()
        L.backward()
        optimizer.step()

        sumL += L.item()
    return sumL

for epoch in range(epochs):
    ls = fit(net,batch_size, X, Y)
    if epoch % 100 == 0:
        print(f"{epoch}\t:\tloss = {ls}")


/var/folders/q3/78sc2wx560d0lpbv1cdk0pp80000gn/T/ipykernel_4311/1696175380.py:14: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(F.normalize(x.abs()))


0	:	loss = 59.04846739768982
100	:	loss = 48.85980352759361
200	:	loss = 46.21886941790581
300	:	loss = 46.0106665790081
400	:	loss = 45.74805995821953
500	:	loss = 47.54039481282234
600	:	loss = 44.47279593348503
700	:	loss = 44.21806201338768
800	:	loss = 45.17453944683075
900	:	loss = 49.82772806286812
1000	:	loss = 44.362138122320175
1100	:	loss = 44.25276440382004
1200	:	loss = 44.09521636366844
1300	:	loss = 44.14911690354347
1400	:	loss = 43.885205179452896
1500	:	loss = 43.87515780329704
1600	:	loss = 44.41642487049103
1700	:	loss = 44.60721352696419
1800	:	loss = 44.10296148061752
1900	:	loss = 48.129088401794434
2000	:	loss = 45.44622287154198
2100	:	loss = 45.554605573415756
2200	:	loss = 48.56996729969978
2300	:	loss = 45.23025315999985
2400	:	loss = 44.12079781293869
2500	:	loss = 46.19621363282204
2600	:	loss = 45.92580443620682
2700	:	loss = 44.80602365732193
2800	:	loss = 48.64179041981697
2900	:	loss = 47.25073429942131
3000	:	loss = 46.291977763175964
3100	:	loss = 44